title: "SMC Presales Accelerators"
remote_theme: jekyll/minima

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - about.md

minima:
  skin: auto


collections_dir: Content
collections:
  fabric:
    output: true
  arc_enabled_sql:
    output: true